/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ff9238",
        "primary-container": "#ef8529",
        "primary-dim": "#ec8327",
        "primary-fixed": "#f68a2f",
        "primary-fixed-dim": "#e57d21",
        "secondary": "#6ebaf7",
        "secondary-container": "#006497",
        "secondary-dim": "#5face8",
        "secondary-fixed": "#aad6ff",
        "secondary-fixed-dim": "#8bcaff",
        "tertiary": "#d4e7ff",
        "tertiary-container": "#c3d9f3",
        "tertiary-dim": "#b6cbe5",
        "tertiary-fixed": "#c3d9f3",
        "tertiary-fixed-dim": "#b6cbe5",
        "error": "#ff7351",
        "error-container": "#b92902",
        "error-dim": "#d53d18",
        "background": "#000f1e",
        "surface": "#000f1e",
        "surface-bright": "#0e2e48",
        "surface-dim": "#000f1e",
        "surface-variant": "#09283f",
        "surface-tint": "#ff9238",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#001526",
        "surface-container": "#021b2f",
        "surface-container-high": "#052137",
        "surface-container-highest": "#09283f",
        "on-primary": "#4c2300",
        "on-primary-container": "#3b1a00",
        "on-primary-fixed": "#0f0400",
        "on-primary-fixed-variant": "#502500",
        "on-secondary": "#003654",
        "on-secondary-container": "#f4f8ff",
        "on-secondary-fixed": "#003757",
        "on-secondary-fixed-variant": "#005582",
        "on-tertiary": "#40556b",
        "on-tertiary-container": "#384d62",
        "on-tertiary-fixed": "#253a4e",
        "on-tertiary-fixed-variant": "#41566c",
        "on-surface": "#d4e7fe",
        "on-surface-variant": "#9aadc3",
        "on-background": "#d4e7fe",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "inverse-surface": "#f7f9ff",
        "inverse-on-surface": "#45576a",
        "inverse-primary": "#954b00",
        "outline": "#65778b",
        "outline-variant": "#384a5c",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
